/**
 * @scee/db
 * --------
 * This package provides the centralized Prisma Database Client for the whole monorepo.
 * 
 * Flow:
 * 1. `prisma generate` creates the TypeScript client from `schema.prisma`.
 * 2. We export a singleton instance of `PrismaClient` to prevent exhausting 
 *    Postgres connection limits during development (Hot Module Replacement).
 */
import { PrismaClient } from "@prisma/client";

// Singleton pattern for Prisma Client (standard best practice)
const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log:
      process.env.NODE_ENV === "development"
        ? ["warn", "error"]
        : ["error"],
  });

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}

// Re-export all model types generated by Prisma
export * from "@prisma/client";

